version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - im-server
    ports:
      - 80:80
      - 443:443
  im-server:
    build: .
    volumes:
      - ./:/home/app
    ports:
      - 3002:3001
    network_mode: "host"
    env_file:
      - ./.env